# Configuration for moving issue(s) workflow.
#
# Delete the command comment when it contains no other content.
# If disabled, workflow won't delete specified commands.
deleteCommand: true

# Close the source issue after moving.
# If disabled, after moving an issue, source won't be closed.
closeSourceIssue: true

# Lock the source issue after moving.
# If disabled, after moving an issue, source won't be locked.
lockSourceIssue: false

# Mention issue and comment authors.
# If disabled, after moving an issue, worflow won't mention all of the participants.
mentionAuthors: false

# Preserve mentions in the issue content.
# If disabled, workflow won't preserve mentions inside the issue.
keepContentMentions: true

# Move labels that also exist on the target repository.
# If disabled, workflow won't move the labels of source issue.
# If any label doesn't exist on further repository, then the label won't be moved.
moveLabels: true

# Set custom aliases for targets.
# If inside organization, you can specify your own repository by ignoring the owner.
# aliases:
#   r: repo
#   or: owner/repo

# Repository to extend settings from specified path.
# _extends: repo